export const defaultUserSelect = {
  id: true,
  createdAt: true,
  username: true,
  email: true,
  phone: true,
  isPremium: true,
  premiumStart: true,
  premiumEnd: true,
  profilePicPath: true,
  dateOfBirth: true,
  address: true,
  website: true,
  bio: true,
  cvPath: true,
  school: true,
  degree: true,
  studyField: true,
  grade: true,
  gender: true,
  role: true,
};
